### ISSUE TITLE
Vial key order is not left to right unlike other keyboards

### ISSUE THREAD

**Issue by HubKing** [Squalius-cephalus/silakka54#4]
I bought it from AliExpress, and with the firmware it came, this happened. When I tested Vial with a different keyboard model, the keys were filled from left to right, as I had expected.

I just updated the firmware with the version you released (8 layers), and the problem is the same. Is this because a wrong firmware setting, or is this because the Chinese manufacturer soldered something incorrectly?

https://github.com/user-attachments/assets/48db2cd4-dd0b-415f-a81c-489b6d97e8cb

**Comment by anwerd** [comment]
Looks like this is an issue with the Vial GUI rather than the firmware itself.
https://github.com/vial-kb/vial-gui/issues/123

**Comment by HubKing** [comment]
Thanks for your research. It seems that something was merged in August 2024 on that thread. Does it mean that it is already fixed, just not available yet?

**Comment by TweetyDaBird** [comment]
This is a combination of both those issues really. The Vial GUI has no inherent knowledge of the positions of the keys, sop it follows the order in the keymap and vial.json. The 'fix' was implemented to actually follow the .json order correctly, but if that is badly ordered, you get your result. I'd start by making that ordered, re-compile and test. If the error then persist, it _may_ be a GUI error still.

**Comment by Dregu** [comment]
Was immediately annoyed by this when I got my keeb, tried doing the column stagger more correctly, but vial gui still jumped all over the place based on the y-positions, so ended up with this more simple layout, which at least works in order. The current fancier json isn't even very close to the actual layout, must be from some different board...

```json
{
    "matrix": {
        "rows": 10,
        "cols": 6
    },
    "layouts": {
        "keymap": [
            ["0,0", "0,1", "0,2", "0,3", "0,4", "0,5", { "x": 1 }, "5,5", "5,4", "5,3", "5,2", "5,1", "5,0"],
            ["1,0", "1,1", "1,2", "1,3", "1,4", "1,5", { "x": 1 }, "6,5", "6,4", "6,3", "6,2", "6,1", "6,0"],
            ["2,0", "2,1", "2,2", "2,3", "2,4", "2,5", { "x": 1 }, "7,5", "7,4", "7,3", "7,2", "7,1", "7,0"],
            ["3,0", "3,1", "3,2", "3,3", "3,4", "3,5", { "x": 1 }, "8,5", "8,4", "8,3", "8,2", "8,1", "8,0"],
                     [{ "x": 3 }, "4,3", "4,4", "4,5", { "x": 1 }, "9,5", "9,4", "9,3"]
        ]
    }
}
```

**Comment by Squalius-cephalus** [comment]
I've tested Vial GUI with the fixed layout from the [QMK repo](https://github.com/qmk/qmk_firmware/commit/c4ccbf06e147ce8d50b2629fb32e39ce56b4fb04) and the problem still persists.

Currently only working solution is to make layout ortholinear(like how @Dregu has done) on vial json, but I don't really like how much it differs visually from the keyboard's own layout. 

<img width="736" height="323" alt="Image" src="https://github.com/user-attachments/assets/99536bce-3ba4-457a-bf8b-9ca7f6e81a63" />
